services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  AchttienVijftien\Stud\Boot\:
    resource: '../../stud/src/Boot'

  AchttienVijftien\Stud\Boot\Boot:
    arguments:
      - !tagged_iterator stud.bootable

  AchttienVijftien\Stud\Hook\:
    resource: '../../stud/src/Hook'

  AchttienVijftien\Stud\Hook\Hook:
    arguments:
      - !tagged_iterator stud.hookable

  AchttienVijftien\Stud\Structure\:
    resource: '../../stud/src/Structure'
    exclude: '../../stud/src/Structure/Registrar/*'
