services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  AchttienVijftien\Stud\Fire\:
    resource: '../../stud/src/Fire'
    autowire: false

  AchttienVijftien\Stud\Fire\FireHooks:
    public: true

  AchttienVijftien\Stud\Hook\:
    resource: '../../stud/src/Hook'

  AchttienVijftien\Stud\Structure\:
    resource: '../../stud/src/Structure'
    exclude: '../../stud/src/Structure/Registrar/*'
